spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.96.129:3306/spot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml

server:
  port: 8089
